version: '3'

networks:
  project:

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx_lead_form
    ports:
      - "8011:80"
    volumes:
      - ./dist:/var/www/html:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      project:

  npm:
    image: node:16-alpine3.11
    container_name: npm_lead_form
    volumes:
      - ./:/var/www/html
    ports:
      - "3000:3000"
      - "3001:3001"
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - project